api_platform:
    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header
    title: Hello API Platform
    version: 1.0.0
    # Good defaults for REST APIs
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        pagination_client_items_per_page: true
        extra_properties:
            standard_put: true
    collection:
        pagination:
            items_per_page_parameter_name: num # Default value
